defaults:
    - _self_
    - general : general_default
    - model : discrete
    - train : train_default
    - dataset : qm9

hydra:
  job:
    chdir: True
  run:
    dir: ${oc.env:WORK}/dicrn/${now:%Y-%m-%d}/${general.name}-${now:%H-%M-%S}




